App\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                  min: 3
                  max: 50
                  minMessage: 'Name must be more than 3 characters'
                  maxMessage: 'Name can not be more than 50 characters'
        price:
          - Range:
              min: 10
              max: 5000
              minMessage: 'The price must be at least {{ limit }} € to enter'
              maxMessage: 'The price cannot be more than {{ limit }} € to enter'
        description:
          - NotBlank: ~
        releasedAt:
          - DateTime: ~